from itertools import chain

PLANTER_STATION_ROW_1_START = 14
PLANTER_STATION_ROW_1_END = 10
PLANTER_STATION_ROW_2_START = 7
PLANTER_STATION_ROW_2_END = 3
PLANTER_STATIONS = list[int](
    chain[int](
        range(PLANTER_STATION_ROW_1_START, PLANTER_STATION_ROW_1_END - 1, -1),
        range(PLANTER_STATION_ROW_2_START, PLANTER_STATION_ROW_2_END - 1, -1),
    )
)
NUM_PLANTERS = len(PLANTER_STATIONS)
HARVEST_DROP_STATION = 9
SEED_PICKUP_STATION = 8
